---
- name: Copy Binaries for privesc
  hosts: ubuntu
  become: true
  tasks:
    - name: Install build-essential package
      become: yes
      package:
        name: build-essential
        state: present

    - name: Install gcc-multilib package
      become: yes
      package:
        name: gcc-multilib
        state: present

    - name: Copy shadow-butchers-client source code
      template:
        src: ../../shadow-butchers/src/shadow-butchers-client.c
        dest: /home/{{remote_username}}/shadow-butchers-client.c

    - name: Copy shadow-butchers-premium source code
      template:
        src: ../../shadow-butchers/src/shadow-butchers-premium.c
        dest: /home/{{remote_username}}/shadow-butchers-premium.c

    - name: Copy Makefile
      template:
        src: ../../shadow-butchers/src/Makefile
        dest: /home/{{remote_username}}/Makefile

    - name: Run make to compile
      become: yes
      command: make -C /home/{{remote_username}}/

    - name: Check if ASLR is already disabled
      shell: cat /proc/sys/kernel/randomize_va_space
      register: aslr_status
      ignore_errors: yes

    - name: Disable ASLR if not already disabled
      sysctl:
        name: kernel.randomize_va_space
        value: 0
        state: present
      when: aslr_status.stdout != "0"

    - name: Check if ASLR is successfully disabled
      shell: cat /proc/sys/kernel/randomize_va_space
      register: aslr_new_status

    - name: Print status message
      debug:
        msg: "ASLR has been disabled successfully."
      when: aslr_new_status.stdout == "0"

    - name: Set SETUID bit
      become: yes
      shell: chmod +s /home/{{remote_username}}/shadow-butchers-client

    - name: Change owner of the file
      become: yes
      file:
        path: /home/{{remote_username}}/shadow-butchers-client
        owner: root
        group: root

    - name: Delete shadow-butchers-client.c
      ansible.builtin.file:
        path: /home/{{remote_username}}/shadow-butchers-client.c
        state: absent

    - name: Delete shadow-butchers-premium.c
      ansible.builtin.file:
        path: /home/{{remote_username}}/shadow-butchers-premium.c
        state: absent

    - name: Delete Makefile
      ansible.builtin.file:
        path: /home/{{remote_username}}/Makefile
        state: absent

    # COMMENT THIS WHEN BUILDING FINAL MACHINE
    - name: Copy file exploit for testing exploit
      template:
        src: ../../shadow-butchers/exploit/exploit.py
        dest: /home/{{remote_username}}/exploit.py


