---
- name: Setup FTP Server on Ubuntu
  hosts: ubuntu
  become: true
  tasks:
    - name: Install vsftpd package
      apt:
        name: vsftpd
        state: present

    - name: Copy vsftpd config file
      template:
        src: config/vsftpd.conf
        dest: /etc/vsftpd.conf

    - name: Create FTP directory
      file:
        path: /var/ftp/easy
        state: directory
        owner: nobody
        group: nogroup
        mode: '0755'

    - name: Ensure vsftpd service is enabled
      systemd:
        name: vsftpd
        enabled: yes
        state: restarted
        
    - name: Place file for download
      copy:
        src: files/sql_backup.zip
        dest: /var/ftp/easy/sql_backup.zip

    - name: Place file for notify new url
      copy:
        src: files/leavemehere.txt
        dest: /var/ftp/easy/leavemehere.txt

    - name: Open passive mode ports in firewall
      ufw:
        rule: allow
        port: "{{ item }}"
        comment: "Allow FTP Passive Mode"
        state: enabled
      loop: "{{ range(40000, 40005)|list }}"

    - name: Start vsftpd service if not already running
      service:
        name: vsftpd
        state: started
        enabled: yes