---
- name: Build the application
  hosts: ubuntu
  become: yes
  gather_facts: no
  ignore_errors: yes
  tasks:

    - name: Remove node_modules directory
      ansible.builtin.file:
        path: /var/www/{{project_lbl}}/node_modules
        state: absent
      ignore_errors: yes

    - name: Remove package-lock.json
      ansible.builtin.file:
        path: /var/www/{{project_lbl}}/package-lock.json
        state: absent
      ignore_errors: yes
      
    - name: Install project dependencies and run build script
      npm:
        path: /var/www/{{ project_lbl }}
        global: no
        state: present
        name: install
      become: yes

    - name: Build app
      shell:
        cmd: npm run build
      args:
        chdir: "/var/www/{{ project_lbl }}"
      become: yes



        
