- import_playbook: install_ssh.yaml
- import_playbook: install_dep.yaml
- import_playbook: compress_app.yaml
- import_playbook: transfer_app.yaml
- import_playbook: build_app.yaml
- import_playbook: startup.yaml