---
- name: Install NVM, PM2, Nginx
  hosts: ubuntu
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - git
        - build-essential
        - libssl-dev
        - libffi-dev
        - python3
        - python3-pip
        - nginx

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Execute Node script
      shell:
        cmd: curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash -
    
    - name: Install Node.js and npm
      shell: sudo apt-get install -y nodejs

    - name: Install PM2 globally using npm
      npm:
        name: pm2
        global: yes

    - name: Configure Nginx
      become: yes
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/{{project_name}}
      notify:
        - Reload Nginx

    - name: Enable Nginx site
      become: yes
      file:
        src: /etc/nginx/sites-available/{{project_name}}
        dest: /etc/nginx/sites-enabled/{{project_name}}
        state: link

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-available/default
        state: absent
    - name: Remove default Nginx folder
      file:
        path: /var/www/html
        state: absent

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp
        
  handlers:
    - name: Reload Nginx
      become: yes
      service:
        name: nginx
        state: reloaded

 