---
- name: Install NVM, PM2, Nginx, and deploy project
  hosts: ubuntu
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - git
        - build-essential
        - libssl-dev
        - libffi-dev
        - python3
        - python3-pip
        - nginx

    - name: Create NVM destination directory
      ansible.builtin.file:
        path: /home/user/tools/
        state: directory
        owner: user

    - name: Load NVM script
      become_user: user
      copy:
        src: ./tools/nvm.sh
        dest: /home/user/tools/nvm.sh
      
    - name: Execute NVM script
      become_user: user
      shell: bash /home/user/tools/nvm.sh

    - name: Install Node.js using NVM
      become_user: user
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install node

    - name: Install PM2 globally
      become_user: user
      shell: >
        bash -c 'source ~/.nvm/nvm.sh && nvm use node && npm install -g pm2 --force'


    - name: Install Node.js and npm
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - npm

    - name: Configure Nginx
      become: yes
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/{{project_name}}
      notify:
        - Reload Nginx

    - name: Enable Nginx site
      become: yes
      file:
        src: /etc/nginx/sites-available/{{project_name}}
        dest: /etc/nginx/sites-enabled/{{project_name}}
        state: link

  handlers:
    - name: Reload Nginx
      become: yes
      service:
        name: nginx
        state: reloaded
