---
- name: Post Operation on Ubuntu Server
  hosts: ubuntu
  become: yes
  tasks:
    
    - name: Remove update-motd files
      file:
        path: "/etc/update-motd.d/{{ item }}"
        state: absent
      with_items:
        - 00-header
        - 10-help-text
        - 50-motd-news
        - 50-landscape-sysinfo
        - 80-livepatch
        - 85-fwupd
        - 90-updates-available
        - 95-hwe-eol
        - 88-esm-announce
        - 91-release-upgrade
        - 92-unattended-upgrades
        - 98-fsck-at-reboot
        - 98-reboot-required
        - 97-overlayroot
        - 98-unattended-upgrades
    
    - name: Ensure MOTD file exists
      file:
        path: /etc/motd
        state: touch

    - name: Add custom message to MOTD file
      lineinfile:
        path: /etc/motd
        line: "ПРЕДУПРЕЖДЕНИЕ: Эта система находится под постоянным наблюдением агентства GRILL (Government Reconnaissance of Infiltration, Larceny, and Lusciousness). Несанкционированный доступ будет расценен как пережаренный стейк - тщательно сожжен. 🔥🥩
        ---
        0xE - vC0rp"
        insertafter: EOF

    - name: Ensure port 3100 is blocked (via ufw)
      ufw:
        rule: reject
        port: 3100

    - name: Configure rsyslog
      lineinfile:
        path: /etc/rsyslog.conf
        regexp: "^\\$SystemLogRateLimit"
        line: "$SystemLogRateLimitInterval 0"
        state: present
      notify:
        - restart rsyslog

  handlers:
    - name: restart rsyslog
      service:
        name: rsyslog
        state: restarted