---
- name: Prepare Ubuntu Server
  hosts: ubuntu
  become: yes
  tasks:
    - name: Update apt package cache and upgrade packages
      apt:
        update_cache: yes

    - name: Configure firewall rules
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
        comment: "Allow SSH and other necessary ports"
        state: enabled
      loop:
        - 21 
        - 22 
        - 80 
        - 443
      
    - name: Add user Matteo
      user:
        name: matteo
        password: "{{ 'ilovedgrilledsausages' | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo
        append: yes

    - name: Create home directory for Matteo
      file:
        path: /home/matteo
        state: directory
        owner: matteo
        group: matteo
        mode: '0755'

    - name: Create .ssh directory for Matteo
      file:
        path: /home/matteo/.ssh
        state: directory
        owner: matteo
        group: matteo
        mode: '0700'

    - name: Create a login banner with NSA reference and grilling humor
      copy:
        content: |
          ⚠️ WARNING: This system is under constant surveillance by the GRILL (Government Reconnaissance of Infiltration, Larceny, and Lusciousness) agency. Unauthorized access will be treated like an overcooked steak - thoroughly burnt. 🔥🥩
        dest: /etc/issue.net

    - name: Set Russian language for root user
      lineinfile:
        path: /root/.bashrc
        line: 'export LANG=ru_RU.UTF-8'
        create: yes

    - name: Add {{ansible_ssh_user}} user to sudo group
      user:
        name: "{{ansible_ssh_user}}"
        groups: sudo
        append: yes


  # handlers:
  #   - name: restart sshd
  #     service:
  #       name: sshd
  #       state: restarted
