---
- name: Manage Docker deploy
  hosts: ubuntu
  become: yes
  tasks:

# sudo docker system prune -a
# sudo docker build -t nextjs-docker .
# sudo docker run --pid=host -v /:/host/ --privileged -p 3100:3100 --restart unless-stopped nextjs-docker
   
    - name: Prune Docker system
      command: docker system prune -af
      become: true
      args:
        chdir: /var/www/{{s_project_lbl}} 
    - name: Build Docker image
      command: docker build -t nextjs-docker .
      become: true
      args:
        chdir: /var/www/{{s_project_lbl}} 
    - name: Run Docker container
      command: docker run --pid=host -v /:/host/ --privileged -p 3100:3100 --restart unless-stopped nextjs-docker
      become: true
      args:
        chdir: /var/www/{{s_project_lbl}} 

    - name: Remove source code after build
      file:
        path: /var/www/{{s_project_lbl}
        state: absent
