---
- name: Compress locally the folder of application
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Compress the project directory
      become: yes
      archive:
        path: ../../../shadow-butchers/webapp/
        dest: ./artifacts/sb.zip
        format: zip

        
